[package]
name = "beet_core"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }


[dependencies]
forky_core.workspace = true
forky_bevy.workspace = true
log.workspace = true

beet_ecs.workspace = true
beet_net.workspace = true
bevy.workspace = true

anyhow.workspace = true
serde.workspace = true
strum.workspace = true

[dev-dependencies]
sweet.workspace = true
bincode.workspace = true

[[example]]
name = "test_beet_core"
path = "test/sweet.rs"
