# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[package]
name = "beet"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["ml", "animation", "assets", "ui", "net"]
ml = ["dep:beet_ml"]
net = ["dep:beet_net"]
ui = ["beet_core/ui"]
assets = ["beet_core/assets"]
animation = ["beet_core/animation"]
reflect = ["beet_ecs/reflect"]
tokio = ["beet_net/tokio"]

# dynamic_linking = ["bevy/dynamic_linking"]

[dependencies]
beet_ecs.workspace = true
beet_core.workspace = true
beet_ml = { workspace = true, optional = true }
beet_net = { workspace = true, optional = true }

[dev-dependencies]
beet_examples.workspace = true
bevy = { workspace = true, default-features = true }
log.workspace = true
pretty_env_logger.workspace = true
forky_bevy.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_log.workspace = true
web-sys.workspace = true
wasm-bindgen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true


### WORKSPACE ################################################################################################z###########################

[workspace.package]
version = "0.0.3"
edition = "2021"
description = "A very flexible AI behavior library for games and robotics."
documentation = "https://beetmash.com/docs/beet"
readme = "README.md"
homepage = "https://beetmash.com/docs/beet"
repository = "https://github.com/mrchantey/beet"
license = "MIT OR Apache-2.0"
keywords = ["beet", "beetmash", "behavior", "game-ai", "robotics"]
categories = [
	"science::robotics",
	"game-development",
	"simulation",
	"wasm",
	"embedded",
]
publish = false

[workspace]
# default resolver
resolver = "2"
members = [
	"crates/beet_examples",
	# "crates/beet",
	"crates/beet_core",
	"crates/beet_ecs",
	"crates/beet_ecs/macros",
	"crates/beet_ml",
	"crates/beet_net",
	"crates/beet_server",
	# "crates/cli",
]
exclude = ["crates/beet_esp"]

[workspace.dependencies]
## internal
beet = { path = "./", version = "0.0.3" }
beet_core = { path = "crates/beet_core", version = "0.0.3", default-features = false }
beet_ecs = { path = "crates/beet_ecs", version = "0.0.3" }
beet_ecs_macros = { path = "crates/beet_ecs/macros", version = "0.0.3" }
beet_ml = { path = "crates/beet_ml", version = "0.0.3" }
beet_net = { path = "crates/beet_net", version = "0.0.3" }
beet_server = { path = "crates/beet_server", version = "0.0.3" }
beet_examples = { path = "crates/beet_examples", version = "0.0.3" }

## local
# forky_core = { path = "../forky/crates/forky/forky_core" }
# forky_bevy = { path = "../forky/crates/forky/forky_bevy" }
# forky_web = { path = "../forky/crates/forky/forky_web", default-features = false }
# sweet = { path = "../forky/crates/sweet", features = ["bevy"] }

forky_core = "0.1.50"
forky_bevy = "0.1.50"
forky_web = "0.1.50"
sweet = { version = "0.1.50", features = ["bevy"] }

## logging
log = "0.4"
pretty_env_logger = "0.4"
console_log = { version = "1.0", features = ["color"] }

## utility
anyhow = "1.0.75"
thiserror = "1.0.60"
bytemuck = "1.13.1"
petgraph = { version = "0.6.4", features = ["serde-1"] }
heck = "0.4"
rand = "0.8"

## async
futures = "0.3"


## async-native
tokio = { version = "1.35", features = ["full"] }
futures-util = { version = "0.3", default-features = false, features = [
	"sink",
	"std",
] }
tokio-tungstenite = { version = "0.21" }

## macros
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

## attributes
num-traits = "0.2.15"
derive_deref = "1.1.1"
strum = { version = "0.26.0", features = ["derive"] }
strum_macros = "0.26.0"
extend = "1.1.2"

# channels
# parking_lot = {version = "0.12", features = ["wasm-bindgen"] } # fast alternative std::sync::Mutex/RwLock
# flume = { version = "0.11", default-features = false, features = ["async"] }
flume = "0.11"

## io
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
ron = "0.8"

## game
bevy = { version = "0.14", default-features = false, features = [
	"bevy_scene",
	"serialize",
	# "bevy_color",
] }


# [target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"

[workspace.dependencies.web-sys]
# [target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
	# HTML
	'Headers',
	'Document',
	'Element',
	'Window',
	"Cache",
	"CacheStorage",
	'HtmlIFrameElement',
	'DomRectReadOnly',
	# Style
	'MediaQueryList',
	# Events
	'MouseEvent',
	'KeyboardEvent',
	'CustomEvent',
	'CustomEventInit',
	# JS
	'Gpu',
	'console',
	'Navigator',
	'Performance',
	# Fetch
	'Request',
	'RequestInit',
	'RequestMode',
	'Response',
	# Blob
	'Blob',
	'BlobEvent',
	'BlobEventInit',
	'BlobPropertyBag',
	# Elements
	'HtmlAnchorElement',
	'HtmlCanvasElement',
	'HtmlInputElement',
	'File',
	'FileList',
	# Url
	'Url',
	'History',
	'Location',
	'UrlSearchParams',
	# indexedDB
	"IdbCursor",
	"IdbCursorDirection",
	"IdbCursorWithValue",
	"IdbDatabase",
	"IdbFactory",
	"IdbFileHandle",
	"IdbFileMetadataParameters",
	"IdbFileRequest",
	"IdbIndex",
	"IdbIndexParameters",
	"IdbKeyRange",
	"IdbLocaleAwareKeyRange",
	"IdbMutableFile",
	"IdbObjectStore",
	"IdbObjectStoreParameters",
	"IdbOpenDbOptions",
	"IdbOpenDbRequest",
	"IdbRequest",
	"IdbRequestReadyState",
	"IdbTransaction",
	"IdbTransactionMode",
	"IdbVersionChangeEvent",
	"IdbVersionChangeEventInit",
]

[[package.metadata.project]]
name = "app-basic"
thumb-text = "🐛"
description = "Basic Beet App with debugging, camera, and UI."

[[package.metadata.project]]
name = "app-full"
thumb-text = "🐛"
description = "Full Beet App with machine learning, networking, and UI."

[[package.metadata.project]]
name = "beet-debug"
thumb-text = "🐛"
description = "Enable debugging for printing to the console, and screen if used with ui-terminal."
scene.path = "scenes/beet-debug.ron"

[[package.metadata.project]]
name = "beet-debug"
thumb-text = "🐛"
description = "Enable debugging for printing to the console, and screen if used with ui-terminal."
scene.path = "scenes/beet-debug.ron"

[[package.metadata.project]]
name = "ui-terminal"
thumb-text = "🖥️"
description = "On-screen terminal outputs beet-debug messages."
scene.path = "scenes/ui-terminal.ron"

[[package.metadata.project]]
name = "ui-terminal-input"
thumb-text = "🖥️"
description = "On-screen terminal with support for user input."
scene.path = "scenes/ui-terminal-input.ron"

[[package.metadata.project]]
name = "camera-2d"
thumb-text = "📸"
description = "2D camera for rendering 2D scenes."
scene.path = "scenes/camera-2d.ron"

[[package.metadata.project]]
name = "camera-3d"
thumb-text = "📸"
description = "3D camera for rendering 3D scenes."
scene.path = "scenes/camera-3d.ron"

[[package.metadata.project]]
name = "ground-3d"
thumb-text = "🏝️"
description = "A simple 3D ground plane."
scene.path = "scenes/ground-3d.ron"

[[package.metadata.project]]
name = "lighting-3d"
thumb-text = "💡"
description = "A directional light configured with shadows."
scene.path = "scenes/lighting-3d.ron"

[[package.metadata.project]]
name = "space-scene"
thumb-text = "🌌"
description = "A 2D space scene with a starry background and transform wrap-around."
scene.path = "scenes/space-scene.ron"

[[package.metadata.project]]
name = "hello-world"
thumb-text = "🌍"
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-world.png"
description = "A simple behavior that prints 'Hello' then 'World' to the console."
scene.path = "scenes/hello-world.ron"
scene.dependencies = ["beet-debug", "camera-2d", "ui-terminal"]


[[package.metadata.project]]
name = "hello-net"
description = "A simple behavior demonstrating triggering and reacting to network events."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-net.png"
scene.path = "scenes/hello-net.ron"
scene.dependencies = ["beet-debug", "camera-2d", "ui-terminal"]

[[package.metadata.project]]
name = "hello-animation"
description = "A simple behavior demonstrating animation control."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-animation.png"
scene.path = "scenes/hello-animation.ron"
scene.dependencies = ["beet-debug", "ui-terminal", "lighting-3d", "ground-3d"]

[[package.metadata.project]]
name = "flock"
description = "Demonstration of flocking behaviors."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/flock.png"
scene.path = "scenes/flock.ron"
scene.dependencies = ["beet-debug", "camera-2d", "space-scene"]
app = "app-basic"

[[package.metadata.project]]
name = "seek"
description = "Demonstration of the seek behavior."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/seek.png"
scene.path = "scenes/seek.ron"
scene.dependencies = ["beet-debug", "camera-2d", "space-scene"]

[[package.metadata.project]]
name = "seek-3d"
description = "A 3D demonstration of the seek behavior."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/seek-3d.png"
scene.path = "scenes/seek-3d.ron"
scene.dependencies = ["beet-debug", "lighting-3d", "ground-3d"]

[[package.metadata.project]]
name = "hello-llm"
description = "A behavior that uses a Sentence Selector to score child behaviors, deciding which will run next."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-llm.png"
scene.path = "scenes/hello-llm.ron"
scene.dependencies = ["beet-debug", "camera-2d", "ui-terminal"]

[[package.metadata.project]]
name = "fetch-npc"
description = "The fetch character that will interact with the player."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/fetch.png"
scene.path = "scenes/fetch-npc.ron"
app = "app-full"

[[package.metadata.project]]
name = "fetch-scene"
thumb-text = "🏠"
description = "A camera and the items that the fetch character can go to."
scene.path = "scenes/fetch-scene.ron"

[[package.metadata.project]]
name = "fetch"
description = "Combining LLM, steering and animation behaviors."
scene.path = "scenes/fetch.ron"
scene.dependencies = [
	"beet-debug",
	"fetch-scene",
	"ui-terminal-input",
	"lighting-3d",
	"ground-3d",
	"fetch-npc",
]
events.playerMessage.initial = "I'm hungry!"

[[package.metadata.project]]
name = "frozen-lake-scene"
thumb-text = "❄️"
description = "The static scene for the frozen lake environment."
scene.path = "scenes/frozen-lake-scene.ron"


[[package.metadata.project]]
name = "train"
description = "Train a Q-learning agent to navigate the frozen lake environment."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/frozen-lake-run.png"
scene.path = "scenes/frozen-lake-train.ron"
scene.dependencies = [
	"beet-debug",
	"frozen-lake-scene",
	"ui-terminal",
	"lighting-3d",
]

[[package.metadata.project]]
name = "infer"
description = "Use a trained Q-learning agent to navigate the frozen lake environment."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/frozen-lake-run.png"
scene.path = "scenes/frozen-lake-run.ron"
scene.dependencies = [
	"beet-debug",
	"frozen-lake-scene",
	"ui-terminal",
	"lighting-3d",
]
