# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[workspace.package]
version = "0.0.4-rc.1"
edition = "2021"
description = "A very flexible AI behavior library for games and robotics."
documentation = "https://beetmash.com/docs/beet"
readme = "README.md"
homepage = "https://beetmash.com/docs/beet"
repository = "https://github.com/mrchantey/beet"
license = "MIT OR Apache-2.0"
keywords = ["beet", "beetmash", "behavior", "game-ai", "robotics"]
categories = [
	"science::robotics",
	"game-development",
	"simulation",
	"wasm",
	"embedded",
]
publish = false

[workspace]
# default resolver
resolver = "2"
members = [
	"crates/beet_flow/macros",
	"crates/beet_flow",
	"crates/beet_ml",
	"crates/beet_spatial",
	"crates/beet_examples",
]

[workspace.dependencies]
## internal
beet = { path = "./", version = "0.0.4-rc.1" }
beet_spatial = { path = "crates/beet_spatial", version = "0.0.4-rc.1", default-features = false }
beet_flow = { path = "crates/beet_flow", version = "0.0.4-rc.1" }
beet_flow_macros = { path = "crates/beet_flow/macros", version = "0.0.4-rc.1" }
beet_ml = { path = "crates/beet_ml", version = "0.0.4-rc.1" }
beet_examples = { path = "crates/beet_examples", version = "0.0.4-rc.1" }

## local
beetmash = { version = "0.0.6-rc.1", path = "../beetmash" }
forky_core = { version = "0.1.50", path = "../forky/crates/forky_core" }
forky_bevy = { version = "0.1.50", path = "../forky/crates/forky_bevy" }
forky_web = { version = "0.1.50", path = "../forky/crates/forky_web", default-features = false }
sweet = { version = "0.1.50", path = "../sweet", features = ["bevy"] }

# beetmash = "0."
# forky_core = "0.1.50"
# forky_bevy = "0.1.50"
# forky_web = { version = "0.1.50", default-features = false }
# sweet = { version = "0.1.50", features = ["bevy"] }

## logging
log = "0.4"
pretty_env_logger = "0.4"
console_log = { version = "1.0", features = ["color"] }

## utility
anyhow = "1.0.75"
thiserror = "1.0.60"
bytemuck = "1.13.1"
petgraph = { version = "0.6.4", features = ["serde-1"] }
heck = "0.4"
rand = "0.8"

## async
futures = "0.3"


## async-native
tokio = { version = "1.35", features = ["full"] }

## macros
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

## attributes
num-traits = "0.2.15"
derive_deref = "1.1.1"
strum = { version = "0.26.0", features = ["derive"] }
strum_macros = "0.26.0"
extend = "1.1.2"

## io
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ron = "0.8"

## game
# bevy = { version = "0.14", default-features = false, features = [
# 	"bevy_scene",
# 	"serialize",
# 	# "bevy_color",
# ] }
#💡 observer reflect attributes, required until 0.14.1
bevy = { version = "0.14", path = "../bevy", default-features = false, features = [
	"bevy_scene",
	"serialize",
	# "bevy_color",
] }


# [target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"

#💡💡 Package

[package]
name = "beet"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["ml", "animation", "assets", "ui"]
ml = ["dep:beet_ml"]
beetmash = ["dep:beetmash"]
ui = ["beet_spatial/ui"]
assets = ["beet_spatial/assets"]
animation = ["beet_spatial/animation"]
reflect = ["beet_flow/reflect"]

# dynamic_linking = ["bevy/dynamic_linking"]

[dependencies]
beet_flow.workspace = true
beet_spatial.workspace = true
beet_ml = { workspace = true, optional = true }
beetmash = { workspace = true, optional = true }

[dev-dependencies]
beet_examples.workspace = true
bevy = { workspace = true, default-features = true }
log.workspace = true
pretty_env_logger.workspace = true
forky_bevy.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_log.workspace = true
web-sys.workspace = true
wasm-bindgen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true


### WORKSPACE ################################################################################################z###########################

[workspace.dependencies.web-sys]
# [target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
	# HTML
	'Headers',
	'Document',
	'Element',
	'Window',
	"Cache",
	"CacheStorage",
	'HtmlIFrameElement',
	'DomRectReadOnly',
	# Style
	'MediaQueryList',
	# Events
	'MouseEvent',
	'KeyboardEvent',
	'CustomEvent',
	'CustomEventInit',
	# JS
	'Gpu',
	'console',
	'Navigator',
	'Performance',
	# Fetch
	'Request',
	'RequestInit',
	'RequestMode',
	'Response',
	# Blob
	'Blob',
	'BlobEvent',
	'BlobEventInit',
	'BlobPropertyBag',
	# Elements
	'HtmlAnchorElement',
	'HtmlCanvasElement',
	'HtmlInputElement',
	'File',
	'FileList',
	# Url
	'Url',
	'History',
	'Location',
	'UrlSearchParams',
	# indexedDB
	"IdbCursor",
	"IdbCursorDirection",
	"IdbCursorWithValue",
	"IdbDatabase",
	"IdbFactory",
	"IdbFileHandle",
	"IdbFileMetadataParameters",
	"IdbFileRequest",
	"IdbIndex",
	"IdbIndexParameters",
	"IdbKeyRange",
	"IdbLocaleAwareKeyRange",
	"IdbMutableFile",
	"IdbObjectStore",
	"IdbObjectStoreParameters",
	"IdbOpenDbOptions",
	"IdbOpenDbRequest",
	"IdbRequest",
	"IdbRequestReadyState",
	"IdbTransaction",
	"IdbTransactionMode",
	"IdbVersionChangeEvent",
	"IdbVersionChangeEventInit",
]


[[package.metadata.project]]
name = "hello-world"
thumb-text = "🌍"
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-world.png"
description = "A simple behavior that prints 'Hello' then 'World' to the console."
scene.path = "scenes/hello-world.ron"
scene.dependencies = ["beet-debug", "camera-2d", "ui-terminal"]
