[workspace.package]
version = "0.0.8"
edition = "2021"
description = "A very flexible AI behavior library for games and robotics."
documentation = "https://mrchantey.github.io/beet"
readme = "README.md"
homepage = "https://mrchantey.github.io/beet"
repository = "https://github.com/mrchantey/beet"
license = "MIT OR Apache-2.0"
keywords = ["beet", "beetmash", "behavior", "game-ai", "robotics"]
categories = [
	"science::robotics",
	"game-development",
	"simulation",
	"wasm",
	"embedded",
]
publish = false

[workspace]
# default resolver
resolver = "2"
members = [
	"crates/beet",
	"crates/beet_core",
	"crates/beet_ecs",
	"crates/beet_ecs/macros",
	"crates/beet_ml",
	"crates/beet_net",
	"crates/beet_server",
	"crates/beet_web",
	# "crates/beet-cli",
]
exclude = ["crates/beet_esp"]

[workspace.dependencies]
## internal
beet = { path = "crates/beet", version = "0.0.8" }
beet_core = { path = "crates/beet_core", version = "0.0.8" }
beet_ecs = { path = "crates/beet_ecs", version = "0.0.8" }
beet_ecs_macros = { path = "crates/beet_ecs/macros", version = "0.0.8" }
beet_ml = { path = "crates/beet_ml", version = "0.0.8" }
beet_net = { path = "crates/beet_net", version = "0.0.8" }
beet_server = { path = "crates/beet_server", version = "0.0.8" }

## local
forky_core = { path = "../forky/crates/forky/forky_core" }
forky_bevy = { path = "../forky/crates/forky/forky_bevy" }
forky_web = { path = "../forky/crates/forky/forky_web" }
sweet = { path = "../forky/crates/sweet", features = ["bevy"] }

# forky_core = "0.1.46"
# forky_bevy = "0.1.46"
# forky_web = "0.1.46"
# sweet = { version = "0.1.46", features = ["bevy"] }

## logging
log = "0.4"
pretty_env_logger = "0.4"

## utility
anyhow = "1.0.75"
bytemuck = "1.13.1"
petgraph = { version = "0.6.4", features = ["serde-1"] }
heck = "0.4"

## async
futures = "0.3"


## async-native
tokio = { version = "1.35", features = ["full"] }
futures-util = { version = "0.3", default-features = false, features = [
	"sink",
	"std",
] }
tokio-tungstenite = { version = "0.21" }

## macros
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

## attributes
num-traits = "0.2.15"
derive_deref = "1.1.1"
strum = "0.25.0"
strum_macros = "0.25.0"
extend = "1.1.2"

# channels
parking_lot = "0.12" # fast alternative std::sync::Mutex/RwLock
# flume = { version = "0.11", default-features = false, features = ["async"] }
flume = "0.11"

## io
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
bincode = "1.3"
ron = "0.8"

## game
# two requirements for back to release:
# 1. recursive type registration https://github.com/bevyengine/bevy/tree/d3e44325b45daf13087a6fe7a425b1744b5f2379
# 2. remove_by_id https://github.com/bevyengine/bevy/pull/9663
# bevy = { path = "../bevy", default-features = false, features = ["bevy_scene"] }
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "f516de456be2b65572de1af6956d52157663b9cc", default-features = false, features = [
	"bevy_scene",
	# "bevy_color",
] }
