[workspace.package]
version = "0.0.7"
edition = "2021"
description = "AI behavior library for games and robotics."
documentation = "https://mrchantey.github.io/beet"
readme = "README.md"
homepage = "https://mrchantey.github.io/beet"
repository = "https://github.com/mrchantey/beet"
license = "MIT OR Apache-2.0"
keywords = ["beet", "beetmash", "behavior", "game-ai", "robotics"]
categories = [
	"science::robotics",
	"game-development",
	"simulation",
	"wasm",
	"embedded",
]
publish = false

[workspace]
# default resolver
resolver = "2"
members = [
	# "crates/beet",
	"crates/beet_core",
	"crates/beet_ecs",
	"crates/beet_ecs/macros",
	"crates/beet_net",
	"crates/beet_web",
	# "crates/beet-cli",
]

[workspace.dependencies]
## internal
beet = { path = "crates/beet", version = "0.0.7" }
beet_ecs = { path = "crates/beet_ecs", version = "0.0.7" }
beet_core = { path = "crates/beet_core", version = "0.0.7" }
beet_ecs_macros = { path = "crates/beet_ecs/macros", version = "0.0.7" }
beet_net = { path = "crates/beet_net", version = "0.0.7" }

## local
forky_core = { path = "../forky/crates/forky/forky_core" }
forky_bevy = { path = "../forky/crates/forky/forky_bevy" }
forky_web = { path = "../forky/crates/forky/forky_web" }
sweet = { path = "../forky/crates/sweet", features = ["bevy_core"] }

# forky_core = { version = "0.1.43" }
# forky_bevy = { version = "0.1.43" }
# forky_web = { version = "0.1.43" }
# sweet = { version = "0.1.43", features = ["bevy_core"] }

# forky_core = { path = "../forky/crates/forky/forky_core" }
# forky_web = { path = "../forky/crates/forky/forky_web" }

## logging
log = "0.4"
pretty_env_logger = "0.4"

## utility
anyhow = "1.0.75"
bytemuck = "1.13.1"
petgraph = { version = "0.6.4", features = ["serde-1"] }
heck = "0.4.1"

## async
futures = "0.3"
async-broadcast = "0.5" # https://github.com/smol-rs/async-broadcast/issues/50

# flume = "0.11"       # fast alternative to std::sync::mpsc
parking_lot = "0.12" # fast alternative std::sync::Mutex/RwLock
# flume = { version = "0.11", default-features = false, features = ["async"] }

## async-native
tokio = { version = "1.35", features = ["full"] }
futures-util = { version = "0.3", default-features = false, features = [
	"sink",
	"std",
] }
tokio-tungstenite = { version = "0.21" }

## macros
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

## attributes
num-traits = "0.2.15"
derive_deref = "1.1.1"
strum = "0.25.0"
strum_macros = "0.25.0"
extend = "1.1.2"

## io
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
bincode = "1.3"
ron = "0.8"
base64 = "0.22.0"

## game
# bevy = { version = "0.13.*" }
# bevy_app = { version = "0.13.*" }
# bevy_core = { version = "0.13.*" }
# bevy_derive = { version = "0.13.*" }
# bevy_ecs = { version = "0.13.*" }
# bevy_hierarchy = { version = "0.13.*" }
# bevy_math = { version = "0.13.*" }
# bevy_reflect = { version = "0.13.*" }
# bevy_scene = { version = "0.13.*" }
# bevy_tasks = { version = "0.13.*" }
# bevy_time = { version = "0.13.*" }
# bevy_transform = { version = "0.13.*" }
# bevy_utils = { version = "0.13.*" }


# arbitrary sync point https://github.com/bevyengine/bevy/tree/a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838
# allows for recursive type registration
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_app = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_core = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_derive = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_math = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_reflect = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_scene = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_tasks = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_time = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_transform = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
bevy_utils = { git = "https://github.com/bevyengine/bevy.git", rev = "a14793a231ebcfe1d4fce2bdcd6a9d7ea94e1838" }
