# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[workspace.package]
version = "0.0.4-rc.2"
edition = "2021"
description = "A very flexible AI behavior library for games and robotics."
documentation = "https://beetmash.com/docs/beet"
readme = "README.md"
homepage = "https://beetmash.com/docs/beet"
repository = "https://github.com/mrchantey/beet"
license = "MIT OR Apache-2.0"
keywords = ["beet", "beetmash", "behavior", "game-ai", "robotics"]
categories = [
	"science::robotics",
	"game-development",
	"simulation",
	"wasm",
	"embedded",
]
publish = false

[workspace]
# default resolver
resolver = "2"
members = [
	"crates/beet_flow/macros",
	"crates/beet_flow",
	"crates/beet_ml",
	"crates/beet_spatial",
	"crates/beet_examples",
]

[workspace.dependencies]
## internal
beet = { path = "./", version = "0.0.4-rc.2" }
beet_spatial = { path = "crates/beet_spatial", version = "0.0.4-rc.2", default-features = false }
beet_flow = { path = "crates/beet_flow", version = "0.0.4-rc.2" }
beet_flow_macros = { path = "crates/beet_flow/macros", version = "0.0.4-rc.2" }
beet_ml = { path = "crates/beet_ml", version = "0.0.4-rc.2" }
beet_examples = { path = "crates/beet_examples", version = "0.0.4-rc.2" }

## local
beetmash = { version = "0.0.6-rc.2", path = "../beetmash" }
forky = { path = "../forky", version = "0.2.0-rc.3", features = [
	"bevy",
	"web",
] }
sweet = { path = "../sweet", version = "0.2.0-rc.3", features = ["bevy"] }

## logging
log = "0.4"
pretty_env_logger = "0.4"
console_log = { version = "1.0", features = ["color"] }

## utility
anyhow = "1.0.75"
thiserror = "1.0.60"
bytemuck = "1.13.1"
petgraph = { version = "0.6.4", features = ["serde-1"] }
heck = "0.4"
rand = "0.8"

## async
futures = "0.3"


## async-native
tokio = { version = "1.35", features = ["full"] }

## macros
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

## attributes
num-traits = "0.2.15"
derive_deref = "1.1.1"
strum = { version = "0.26.0", features = ["derive"] }
strum_macros = "0.26.0"
extend = "1.1.2"

## io
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ron = "0.8"

#💡 game
# bevy = { version = "0.14", default-features = false, features = [
bevy = { git = "https://github.com/bevyengine/bevy", rev = "0c959f77007c29eead7f902bddd3342a1ecbca20", default-features = false, features = [
	"bevy_scene",
	"serialize",
	# "bevy_color",
] }


# [target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"

#💡 Package

[package]
name = "beet"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["ml", "animation", "assets", "ui", "beetmash"]
ml = ["dep:beet_ml"]
reflect = ["beet_flow/reflect"]
beetmash = ["dep:beetmash"]
animation = ["beet_spatial/animation"]
assets = ["beet_spatial/assets"]
ui = ["beet_spatial/ui"]

# dynamic_linking = ["bevy/dynamic_linking"]

[dependencies]
beet_flow.workspace = true
beet_spatial.workspace = true
beet_ml = { workspace = true, optional = true }
beetmash = { workspace = true, optional = true }
bevy.workspace = true

[dev-dependencies]
bevy = { workspace = true, default-features = true }
beet_examples.workspace = true
log.workspace = true
pretty_env_logger.workspace = true
forky.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_log.workspace = true
web-sys.workspace = true
wasm-bindgen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true


### WORKSPACE ################################################################################################z###########################

[workspace.dependencies.web-sys]
# [target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
	# HTML
	'Headers',
	'Document',
	'Element',
	'Window',
	"Cache",
	"CacheStorage",
	'HtmlIFrameElement',
	'DomRectReadOnly',
	# Style
	'MediaQueryList',
	# Events
	'MouseEvent',
	'KeyboardEvent',
	'CustomEvent',
	'CustomEventInit',
	# JS
	'Gpu',
	'console',
	'Navigator',
	'Performance',
	# Fetch
	'Request',
	'RequestInit',
	'RequestMode',
	'RequestCache',
	'Response',
	# Blob
	'Blob',
	'BlobEvent',
	'BlobEventInit',
	'BlobPropertyBag',
	# Elements
	'HtmlAnchorElement',
	'HtmlCanvasElement',
	'HtmlInputElement',
	'File',
	'FileList',
	# Url
	'Url',
	'History',
	'Location',
	'UrlSearchParams',
	# indexedDB
	"IdbCursor",
	"IdbCursorDirection",
	"IdbCursorWithValue",
	"IdbDatabase",
	"IdbFactory",
	"IdbFileHandle",
	"IdbFileMetadataParameters",
	"IdbFileRequest",
	"IdbIndex",
	"IdbIndexParameters",
	"IdbKeyRange",
	"IdbLocaleAwareKeyRange",
	"IdbMutableFile",
	"IdbObjectStore",
	"IdbObjectStoreParameters",
	"IdbOpenDbOptions",
	"IdbOpenDbRequest",
	"IdbRequest",
	"IdbRequestReadyState",
	"IdbTransaction",
	"IdbTransactionMode",
	"IdbVersionChangeEvent",
	"IdbVersionChangeEventInit",
]

[[package.metadata.scene]]
name = "app"
thumb-text = "🔨"
description = "Basic Beet App with debugging, camera, and UI."
app.js-url = "https://mrchantey.github.io/beetmash-apps/beet/app.js"
app.wasm-url = "https://mrchantey.github.io/beetmash-apps/beet/app_bg.wasm"
app.type-registry-url = "https://mrchantey.github.io/beetmash-apps/beet/registries/type_registry.json"
app.replication-registry-url = "https://mrchantey.github.io/beetmash-apps/beet/registries/replication_registry.json"

[[package.metadata.scene]]
name = "app-ml"
thumb-text = "🔨"
description = "Full Beet App with machine learning, networking, and UI."
app.js-url = "https://mrchantey.github.io/beetmash-apps/beet/app_ml.js"
app.wasm-url = "https://mrchantey.github.io/beetmash-apps/beet/app_ml_bg.wasm"
app.type-registry-url = "https://mrchantey.github.io/beetmash-apps/beet/registries/type_registry_ml.json"
app.replication-registry-url = "https://mrchantey.github.io/beetmash-apps/beet/registries/replication_registry_ml.json"


[[package.metadata.scene]]
name = "beet-debug"
thumb-text = "🐛"
description = "Enable debugging for printing to the console, and screen if used with beetmash/ui-terminal."
path = "scenes/beet-debug.json"

[[package.metadata.scene]]
name = "hello-world"
thumb-text = "🌍"
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-world.png"
description = "A simple behavior that prints 'Hello' then 'World' to the console."
app = "app"
path = "scenes/hello-world.json"
include = ["beet-debug", "beetmash/camera-2d", "beetmash/ui-terminal"]


[[package.metadata.scene]]
name = "flock"
description = "Demonstration of flocking behaviors."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/flock.png"
app = "app"
path = "scenes/flock.json"
include = ["beet-debug", "beetmash/camera-2d", "beetmash/space-scene"]

[[package.metadata.scene]]
name = "seek"
description = "Demonstration of the seek behavior."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/seek.png"
app = "app"
path = "scenes/seek.json"
include = ["beet-debug", "beetmash/camera-2d", "beetmash/space-scene"]

[[package.metadata.scene]]
name = "seek-3d"
description = "A 3D demonstration of the seek behavior."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/seek-3d.png"
app = "app"
path = "scenes/seek-3d.json"
include = ["beet-debug", "beetmash/lighting-3d", "beetmash/ground-3d"]


[[package.metadata.scene]]
name = "hello-animation"
description = "A simple behavior demonstrating animation control."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-animation.png"
app = "app"
path = "scenes/hello-animation.json"
include = [
	"beetmash/ui-terminal",
	"beetmash/lighting-3d",
	"beetmash/ground-3d",
	"beet-debug",
]

[[package.metadata.scene]]
name = "hello-ml"
description = "A behavior that uses a Sentence Selector to score child behaviors, deciding which will run next."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-llm.png"
path = "scenes/hello-ml.json"
include = ["beetmash/camera-2d", "beetmash/ui-terminal", "beet-debug"]

[[package.metadata.scene]]
name = "fetch-scene"
thumb-text = "🏠"
description = "A camera and the items that the fetch character can go to."
path = "scenes/fetch-scene.json"

[[package.metadata.scene]]
name = "fetch"
description = "Combining LLM, steering and animation behaviors."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/fetch.png"
app = "app-ml"
path = "scenes/fetch-npc.json"
include = [
	"beetmash/ui-terminal-input",
	"beetmash/lighting-3d",
	"beetmash/ground-3d",
	"fetch-scene",
]
events.playerMessage.initial = "I'm hungry!"

[[package.metadata.scene]]
name = "frozen-lake-scene"
thumb-text = "❄️"
description = "The static scene for the frozen lake environment."
path = "scenes/frozen-lake-scene.json"


[[package.metadata.scene]]
name = "frozen-lake-train"
description = "Train a Q-learning agent to navigate the frozen lake environment."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/frozen-lake-run.png"
app = "app-ml"
path = "scenes/frozen-lake-train.json"
include = [
	"beetmash/ui-terminal",
	"beetmash/lighting-3d",
	"beet-debug",
	"frozen-lake-scene",
]

[[package.metadata.scene]]
name = "frozen-lake-run"
description = "Use a trained Q-learning agent to navigate the frozen lake environment."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/frozen-lake-run.png"
app = "app-ml"
path = "scenes/frozen-lake-run.json"
include = [
	"beetmash/ui-terminal",
	"beetmash/lighting-3d",
	"beet-debug",
	"frozen-lake-scene",
]
