[package]
name = "beet-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[[bin]]
name = "beet"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow.workspace = true
sweet = { workspace = true, features = ["fs"] }
clap.workspace = true


[dev-dependencies]
sweet = { workspace = true, features = ["test"] }