[package]
name = "beet_net"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["native"]
beet_ecs = ["dep:beet_ecs"]
native = ["dep:tokio", "dep:tokio-tungstenite", "dep:futures-util"]
# default = ["bevy_replicon"]
# bevy_replicon = ["dep:bevy_replicon"]

[dependencies]
beet_ecs = { workspace = true, optional = true }

# bevy_replicon = { path = "../../../../me-ref/bevy_replicon", default-features = false, optional = true }


log.workspace = true
bincode.workspace = true
forky_core.workspace = true
serde.workspace = true
flume.workspace = true
anyhow.workspace = true
extend.workspace = true


strum.workspace = true
strum_macros.workspace = true
# futures.workspace = true
# parking_lot.workspace = true

# strum.workspace = true
# strum_macros.workspace = true


# # from the simple_box example
# crossbeam-channel = "0.5.11"
# clap = { version = "4.4", features = ["derive"] }
# async-compat = "0.2.3"
# derive_more = { version = "0.99", features = ["add", "mul"] }

tokio = { workspace = true, optional = true }
tokio-tungstenite = { workspace = true, optional = true }
futures-util = { workspace = true, optional = true }

# bevy = { version = "0.13", default-features = false }
# bevy = { workspace = true, default-features = false, features = [] }
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "f516de456be2b65572de1af6956d52157663b9cc", default-features = false, features = [
	# "bevy_scene",
] }


# tokio = { workspace = true, optional = true }
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]

[dev-dependencies]
pretty_env_logger.workspace = true
sweet.workspace = true
rand = "0.8.1"
