[package]
name = "beet_net"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]

[dependencies]
# anyhow.workspace = true
# extend.workspace = true
# futures.workspace = true
# parking_lot.workspace = true

# serde.workspace = true
# ron.workspace = true

# strum.workspace = true
# strum_macros.workspace = true


# # from the simple_box example
# crossbeam-channel = "0.5.11"
# clap = { version = "4.4", features = ["derive"] }
# async-compat = "0.2.3"
# derive_more = { version = "0.99", features = ["add", "mul"] }


# # bevy = { version = "0.13", default-features = false }
# bevy.workspace = true
# log.workspace = true

# tokio = { workspace = true, optional = true }
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]

[dev-dependencies]
pretty_env_logger.workspace = true
sweet.workspace = true
rand = "0.8.1"
