[package]
name = "beet_net"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
tokio = ["dep:tokio"]

[dependencies]
anyhow.workspace = true
async-broadcast.workspace = true
extend.workspace = true
futures.workspace = true
parking_lot.workspace = true
serde.workspace = true
bincode.workspace = true
strum.workspace = true
strum_macros.workspace = true

# bevy_ecs.workspace = true
bevy_derive.workspace = true
bevy_utils.workspace = true
log.workspace = true

tokio = { workspace = true, optional = true }
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]

[dev-dependencies]
pretty_env_logger.workspace = true
sweet.workspace = true


[[example]]
name = "test_beet_net"
path = "test/sweet.rs"
required-features = ["tokio"]
