[package]
name = "beet_net"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["beet_ecs", "serde_json"]
beet_ecs = ["dep:beet_ecs"]
serde_json = ["dep:serde_json"]
tokio = ["dep:tokio", "dep:tokio-tungstenite", "dep:futures-util"]
# default = ["bevy_replicon"]
# bevy_replicon = ["dep:bevy_replicon"]

[dependencies]
beet_ecs = { workspace = true, optional = true }

log.workspace = true
bincode.workspace = true
forky_core.workspace = true
serde.workspace = true
serde_json = { workspace = true, optional = true }
flume.workspace = true
anyhow.workspace = true
extend.workspace = true


strum.workspace = true
strum_macros.workspace = true
# futures.workspace = true
# parking_lot.workspace = true

# strum.workspace = true
# strum_macros.workspace = true

bevy = { version = "0.14", default-features = false, features = [
	# "bevy_scene",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, optional = true }
tokio-tungstenite = { workspace = true, optional = true }
futures-util = { workspace = true, optional = true }


[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys.workspace = true
js-sys.workspace = true
forky_web.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true

# tokio = { workspace = true, optional = true }
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]

[dev-dependencies]
pretty_env_logger.workspace = true
sweet.workspace = true
rand.workspace = true
[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true

[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["tokio"]

[[example]]
name = "two_clients"
path = "examples/two_clients.rs"
required-features = ["tokio"]
