[package]
name = "beet_examples"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
beet = { workspace = true, features = [
	"flow",
	"ml",
	"spatial",
	"bevy_default",
] }
serde.workspace = true
serde_json.workspace = true
# beet = { workspace = true, features = ["reflect"] }
bevy = { workspace = true, default-features = true }
# bevy-inspector-egui = "0.25.0"
log.workspace = true
pretty_env_logger.workspace = true
anyhow.workspace = true
sweet = { workspace = true, features = ["bevy", "rand"] }

[dev-dependencies]
sweet = { workspace = true, features = ["test"] }
log.workspace = true
pretty_env_logger.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true


[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_log.workspace = true
web-sys.workspace = true
wasm-bindgen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true


[[example]]
name = "app_ml"
path = "examples/app_ml.rs"

[[package.metadata.scene]]
name = "app-ml"
thumb-text = "🔨"
description = "Full Beet App with machine learning, networking, and UI."
app.js-url = "https://mrchantey.github.io/bevyhub-apps/beet/app_ml.js"
app.wasm-url = "https://mrchantey.github.io/bevyhub-apps/beet/app_ml_bg.wasm"
app.type-registry-url = "https://mrchantey.github.io/bevyhub-apps/beet/registries/type_registry_ml.json"
app.replication-registry-url = "https://mrchantey.github.io/bevyhub-apps/beet/registries/replication_registry_ml.json"

[[example]]
name = "app"
path = "examples/app.rs"

[[package.metadata.scene]]
name = "app"
thumb-text = "🔨"
description = "Basic Beet App with debugging, camera, and UI."
app.js-url = "https://mrchantey.github.io/bevyhub-apps/beet/app.js"
app.wasm-url = "https://mrchantey.github.io/bevyhub-apps/beet/app_bg.wasm"
app.type-registry-url = "https://mrchantey.github.io/bevyhub-apps/beet/registries/type_registry.json"
app.replication-registry-url = "https://mrchantey.github.io/bevyhub-apps/beet/registries/replication_registry.json"

[[package.metadata.scene]]
name = "beet-debug"
thumb-text = "🐛"
description = "Enable debugging for printing to the console, and screen if used with bevyhub/ui-terminal."
path = "scenes/beet-debug.json"

[[example]]
name = "export_scenes"
path = "examples/export_scenes.rs"


[[package.metadata.scene]]
name = "fetch-scene"
thumb-text = "🏠"
description = "A camera and the items that the fetch character can go to."
path = "scenes/fetch-scene.json"

[[example]]
name = "fetch"
path = "examples/fetch.rs"

[[package.metadata.scene]]
name = "fetch"
description = "Combining LLM, steering and animation behaviors."
thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/fetch.png"
app = "app-ml"
path = "scenes/fetch-npc.json"
include = [
	"bevyhub/ui-terminal-input",
	"bevyhub/lighting-3d",
	"bevyhub/ground-3d",
	"fetch-scene",
]
events.playerMessage.initial = "I'm hungry!"

[[package.metadata.scene]]
name = "frozen-lake-scene"
thumb-text = "❄️"
description = "The static scene for the frozen lake environment."
path = "scenes/frozen-lake-scene.json"


[[example]]
name = "frozen_lake_train"
path = "examples/frozen_lake_train.rs"

[[package.metadata.scene]]
name = "frozen-lake-train"
description = "Train a Q-learning agent to navigate the frozen lake environment."
thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/frozen-lake-run.png"
app = "app-ml"
path = "scenes/frozen-lake-train.json"
include = [
	"bevyhub/ui-terminal",
	"bevyhub/lighting-3d",
	"beet-debug",
	"frozen-lake-scene",
]

[[example]]
name = "frozen_lake_run"
path = "examples/frozen_lake_run.rs"

[[package.metadata.scene]]
name = "frozen-lake-run"
description = "Use a trained Q-learning agent to navigate the frozen lake environment."
thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/frozen-lake-run.png"
app = "app-ml"
path = "scenes/frozen-lake-run.json"
include = [
	"bevyhub/ui-terminal",
	"bevyhub/lighting-3d",
	"beet-debug",
	"frozen-lake-scene",
]

# Too big, we need to handle for loops in scene files
# [[package.metadata.scene]]
# name = "flock"
# description = "Demonstration of flocking behaviors."
# thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/flock.png"
# app = "app"
# path = "scenes/flock.json"
# include = ["beet-debug", "bevyhub/camera-2d", "bevyhub/space-scene"]

[[example]]
name = "hello_animation"
path = "examples/hello_animation.rs"


[[package.metadata.scene]]
name = "hello-animation"
description = "A simple behavior demonstrating animation control."
thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/hello-animation.png"
app = "app"
path = "scenes/hello-animation.json"
include = [
	"bevyhub/ui-terminal",
	"bevyhub/lighting-3d",
	"bevyhub/ground-3d",
	"beet-debug",
]


[[example]]
name = "hello_ml"
path = "examples/hello_ml.rs"


[[package.metadata.scene]]
name = "hello-ml"
description = "A behavior that uses a Sentence Selector to score child behaviors, deciding which will run next."
thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/hello-llm.png"
path = "scenes/hello-ml.json"
include = ["bevyhub/camera-2d", "bevyhub/ui-terminal", "beet-debug"]


[[example]]
name = "hello_flow"
path = "examples/hello_flow.rs"

[[package.metadata.scene]]
name = "hello-world"
thumb-text = "🌍"
thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/hello-world.png"
description = "A simple behavior that prints 'Hello' then 'World' to the console."
app = "app"
path = "scenes/hello-world.json"
include = ["beet-debug", "bevyhub/camera-2d", "bevyhub/ui-terminal"]


[[example]]
name = "inverse_kinematics"
path = "examples/inverse_kinematics.rs"


[[package.metadata.scene]]
name = "seek"
description = "Demonstration of the seek behavior."
thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/seek.png"
app = "app"
path = "scenes/seek.json"
include = ["beet-debug", "bevyhub/camera-2d", "bevyhub/space-scene"]

[[package.metadata.scene]]
name = "seek-3d"
description = "A 3D demonstration of the seek behavior."
thumb-url = "https://bevyhub-public.s3.us-west-2.amazonaws.com/assets/screenshots/seek-3d.png"
app = "app"
path = "scenes/seek-3d.json"
include = ["beet-debug", "bevyhub/lighting-3d", "bevyhub/ground-3d"]
