[package]
name = "beet_examples"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []

[dependencies]
forky.workspace = true
beet_flow.workspace = true
beet_spatial.workspace = true
beet_ml.workspace = true
beetmash.workspace = true
# beet = { workspace = true, features = ["reflect"] }
bevy = { workspace = true, default-features = true }
# bevy-inspector-egui = "0.25.0"
log.workspace = true
pretty_env_logger.workspace = true
rand.workspace = true
anyhow.workspace = true

[[example]]
name = "export_scenes"
path = "./examples/export_scenes.rs"