[package]
name = "beet_examples"
publish = false
version.workspace = true
edition.workspace = true

[features]
default = []
tokio = ["beet/tokio"]


[dependencies]
forky_core.workspace = true
# beet = { workspace = true }
beet = { workspace = true, features = ["reflect"] }
bevy = { workspace = true, default-features = true }
log.workspace = true
pretty_env_logger.workspace = true
forky_bevy.workspace = true
rand.workspace = true
flume.workspace = true
serde.workspace = true
anyhow.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
forky_web.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
web-sys.workspace = true

[dev-dependencies]
anyhow.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true


[[example]]
name="export_scenes"
path="./examples/export_scenes.rs"