[package]
name = "beet_examples"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
# to enable reflect we need OnInsert to derive reflect https://github.com/bevyengine/bevy/pull/14259
reflect = ["beet_ecs/reflect"]
tokio = ["beet_net/tokio"]

[dependencies]
forky_core.workspace = true
beet_ecs.workspace = true
beet_core.workspace = true
beet_net.workspace = true
beet_ml.workspace = true
# beet = { workspace = true, features = ["reflect"] }
bevy = { workspace = true, default-features = true }
bevy-inspector-egui = "0.25.0"
log.workspace = true
pretty_env_logger.workspace = true
forky_bevy.workspace = true
rand.workspace = true
flume.workspace = true
serde.workspace = true
anyhow.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
forky_web.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
web-sys.workspace = true

[dev-dependencies]
anyhow.workspace = true
rayon = "1.10.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true


[[example]]
name = "export_scenes"
path = "./examples/export_scenes.rs"
