[package]
name = "beet_examples"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []

[dependencies]
forky_core.workspace = true
beet_flow.workspace = true
beet_spatial.workspace = true
beet_ml.workspace = true
beetmash.workspace = true
# beet = { workspace = true, features = ["reflect"] }
bevy = { workspace = true, default-features = true }
# bevy-inspector-egui = "0.25.0"
log.workspace = true
pretty_env_logger.workspace = true
forky_bevy.workspace = true
rand.workspace = true
anyhow.workspace = true

[[example]]
name = "export_scenes"
path = "./examples/export_scenes.rs"


[[package.metadata.project]]
name = "app-basic"
thumb-text = "🔨"
description = "Basic Beet App with debugging, camera, and UI."
app.js-url = "https://storage.googleapis.com/beet-examples/app_basics/main.js"
app.wasm-url = "https://storage.googleapis.com/beet-examples/app_basics/main_bg.wasm"

[[package.metadata.project]]
name = "app-full"
thumb-text = "🔨"
description = "Full Beet App with machine learning, networking, and UI."
app.js-url = "https://storage.googleapis.com/beet-examples/app_full/main.js"
app.wasm-url = "https://storage.googleapis.com/beet-examples/app_full/main_bg.wasm"

[[package.metadata.project]]
name = "beet-debug"
thumb-text = "🐛"
description = "Enable debugging for printing to the console, and screen if used with ui-terminal."
scene.path = "scenes/beet-debug.ron"

[[package.metadata.project]]
name = "space-scene"
thumb-text = "🌌"
description = "A 2D space scene with a starry background and transform wrap-around."
scene.path = "scenes/space-scene.ron"
