[package]
name = "beet_spatial"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[features]
default = ["animation", "assets", "ui"]
debug_gizmos = ["bevy/bevy_gizmos"]
ui = ["bevy/bevy_ui"]
assets = ["bevy/bevy_asset"]
animation = ["bevy/bevy_animation"]

[dependencies]
forky_core.workspace = true
forky_bevy.workspace = true
beetmash.workspace = true
beet_flow.workspace = true

log.workspace = true
bevy.workspace = true

anyhow.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true

pretty_env_logger.workspace = true

[dev-dependencies]
sweet.workspace = true
