[package]
name = "beet_spatial"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[features]
default = ["animation", "assets", "ui"]
ui = ["bevy/bevy_ui"]
assets = ["bevy/bevy_asset"]
animation = ["bevy/bevy_animation"]
gizmos = ["bevy/bevy_gizmos"]

[dependencies]
forky_core.workspace = true
forky_bevy.workspace = true
beetmash.workspace = true
beet_flow.workspace = true

log.workspace = true
bevy.workspace = true

anyhow.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true

pretty_env_logger.workspace = true

[dev-dependencies]
sweet.workspace = true


[[package.metadata.project]]
name = "flock"
description = "Demonstration of flocking behaviors."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/flock.png"
scene.path = "scenes/flock.ron"
scene.dependencies = ["beet-debug", "camera-2d", "space-scene"]
app = "app-basic"

[[package.metadata.project]]
name = "seek"
description = "Demonstration of the seek behavior."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/seek.png"
scene.path = "scenes/seek.ron"
scene.dependencies = ["beet-debug", "camera-2d", "space-scene"]

[[package.metadata.project]]
name = "seek-3d"
description = "A 3D demonstration of the seek behavior."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/seek-3d.png"
scene.path = "scenes/seek-3d.ron"
scene.dependencies = ["beet-debug", "lighting-3d", "ground-3d"]


[[package.metadata.project]]
name = "hello-animation"
description = "A simple behavior demonstrating animation control."
thumb-url = "https://storage.googleapis.com/beet-examples/screenshots/hello-animation.png"
scene.path = "scenes/hello-animation.ron"
scene.dependencies = ["beet-debug", "ui-terminal", "lighting-3d", "ground-3d"]
