[package]
name = "beet_spatial"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[features]
# default = ["animation", "assets", "ui"]
# bevyhub = []
ui = ["bevy/bevy_ui"]
scene = ["bevy/bevy_scene"]
render = ["bevy/bevy_color", "bevy/bevy_gizmos"]
assets = ["bevy/bevy_asset"]
animation = ["bevy/bevy_animation"]

[dependencies]
beet_flow = { workspace = true }
sweet = { workspace = true, features = ["bevy", "rand"] }
# bevyhub = { workspace = true, optional = true, features = ["core"] }

bevy.workspace = true

extend.workspace = true
anyhow.workspace = true
log.workspace = true
pretty_env_logger.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys.workspace = true

[dev-dependencies]
sweet = { workspace = true, features = ["test"] }
