[package]
name = "beet_ml"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
bevyhub = ["dep:bevyhub"]
spatial = ["dep:beet_spatial"]

[dependencies]
beet_flow.workspace = true
sweet = { workspace = true, features = ["bevy", "rand"] }

bevy = { workspace = true, features = ["bevy_asset", "bevy_scene"] }
bevyhub = { workspace = true, optional = true }
beet_spatial = { workspace = true, optional = true }

futures = "0.3.30"
thiserror.workspace = true
anyhow.workspace = true
log.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true

### huggingface ###
candle-core = "0.5.0"
candle-transformers = "0.5.0"
candle-nn = "0.5.0"
tokenizers = { version = "0.19.1", default-features = false, features = [
	"unstable_wasm",
] }
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hf-hub = "0.3.2"

### web ###
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log.workspace = true
js-sys.workspace = true
web-sys.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
console_error_panic_hook.workspace = true

[dev-dependencies]
sweet = { workspace = true, features = ["test"] }

pretty_env_logger.workspace = true
[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true
