[package]
name = "beet_flow"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[features]
# temp disable reflect until https://github.com/bevyengine/bevy/pull/16018
# default = ["net"]
# default = ["net", "reflect"]
# bevyhub = ["dep:bevyhub"]
net = ["bevyhub", "bevyhub/net"]
bevyhub = ["dep:bevyhub"]
reflect = []

[dependencies]
beet_flow_macros.workspace = true
bevyhub = { workspace = true, optional = true }

log.workspace = true
anyhow.workspace = true
rand.workspace = true
heck.workspace = true
petgraph.workspace = true
serde.workspace = true

extend.workspace = true
num-traits.workspace = true

bevy.workspace = true

[dev-dependencies]
pretty_env_logger.workspace = true
ron.workspace = true
sweet.workspace = true
