[package]
name = "beet_flow"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[features]
default = ["net"]
# beetmash = ["dep:beetmash"]
net = ["dep:beetmash", "beetmash/net"]
# default = ["reflect"]
reflect = []
test = ["dep:sweet"]

[dependencies]
beet_flow_macros.workspace = true
beetmash = { workspace = true, optional = true }

log.workspace = true
anyhow.workspace = true
heck.workspace = true
petgraph.workspace = true
serde.workspace = true

extend.workspace = true
num-traits.workspace = true

bevy.workspace = true
sweet = { workspace = true, optional = true }

[dev-dependencies]
beetmash = { workspace = true, features = ["test"] }
pretty_env_logger.workspace = true
ron.workspace = true
sweet.workspace = true
