[package]
name = "beet_flow"
version.workspace = true
edition.workspace = true
description = "An ECS control flow library"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true


[features]
reflect = ["dep:serde", "bevy/serialize"]
[dependencies]
beet_flow_macros.workspace = true
bevy.workspace = true
log.workspace = true
extend.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
# beet_flow = { path = "" }
sweet = { workspace = true, features = ["test", "bevy"] }
