[book]
title = "Beet"
authors = []
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false
# extra-watch-dirs = ["./custom"]
[output.html]
additional-js = [
	"deps/custom.js",
	"deps/mermaid.min.js",
	"deps/mermaid-init.js",
]
additional-css = ["deps/custom.css"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
