[package]
name = "emby"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
forky.workspace = true
beet.workspace = true
beet_examples.workspace = true
bevyhub.workspace = true
serde.workspace = true
serde_json.workspace = true
# beet = { workspace = true, features = ["reflect"] }
bevy = { workspace = true, default-features = true }
# bevy-inspector-egui = "0.25.0"
log.workspace = true
pretty_env_logger.workspace = true
rand.workspace = true
anyhow.workspace = true

[dev-dependencies]
sweet.workspace = true
