[package]
name = "beet_sim"
version.workspace = true
edition.workspace = true
description = "Simulated environments in which behaviors can be run."
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = true

[features]
default = ["render"]
render = []


[dependencies]
beet_flow.workspace = true
beet_spatial.workspace = true
bevy.workspace = true

anyhow.workspace = true
num-traits.workspace = true
# temp, just for bundle placeholders
beetmash.workspace = true




[dev-dependencies]
bevy = { workspace = true, default-features = true }
beetmash = { workspace = true, features = ["test"] }
sweet.workspace = true